# Generated by Django 6.0.2 on 2026-02-21 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('under_interrogation', 'Under Interrogation'), ('awaiting_captain_verdict', 'Awaiting Captain Verdict'), ('awaiting_chief_verdict', 'Awaiting Chief Verdict'), ('guilty', 'Guilty'), ('not_guilty', 'Not Guilty')], default='under_interrogation', max_length=50)),
                ('wanted_level', models.CharField(default='normal', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='suspects.suspect')),
            ],
        ),
    ]
