# Generated by Django 6.0.2 on 2026-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspect',
            old_name='full_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='wanted_level',
        ),
        migrations.AddField(
            model_name='suspect',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspect',
            name='image',
            field=models.ImageField(null=True, upload_to='suspects/'),
        ),
    ]
