# Generated by Django 6.0.2 on 2026-02-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0002_rename_full_name_suspect_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=models.CharField(choices=[('suspect_created', 'Suspect Created'), ('suspect_verified', 'Suspect Verified'), ('under_interrogation', 'Under Interrogation'), ('awaiting_captain_verdict', 'Awaiting Captain Verdict'), ('awaiting_chief_verdict', 'Awaiting Chief Verdict'), ('guilty', 'Guilty'), ('not_guilty', 'Not Guilty')], default='suspect_created', max_length=50),
        ),
    ]
