# Generated by Django 6.0.2 on 2026-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
