# Generated by Django 6.0.2 on 2026-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_workflowhistory_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('pending_approval', 'Pending Approval'), ('pending_verification', 'Pending Verification'), ('created', 'Created')], default='created', max_length=50),
        ),
    ]
